### PR TITLE
Add GHC 9.8.1 to the cabal CI

### PR DESCRIPTION
**Pull request by mihaimaruseac**
### Checklist

- [ ] Add a changelog if necessary. See https://keepachangelog.com/ for how to write it.
- [ ] Add tests in [TESTS.md](/TESTS.md) if possible.

Part of #760

### CODE REVIEW

**Comment by toku-sa-n** [comment]
@mihaimaruseac Can I override this PR to support GHC 9.8, or should I create another PR?

**Comment by mihaimaruseac** [comment]
Up to you. I didn't get more time to look into it for the past few days :(

**Comment by mihaimaruseac** [comment]
I rebased to remove the merges from master back into the branch as those made understanding the changes harder

**Comment by mihaimaruseac** [comment]
Thank you! This seems to be going through now

**Comment by mihaimaruseac** [comment]
I cannot approve this since I started the PR, but this LGTMs. I enabled auto-merge, if you can approve it will merge automatically once tests finish. Otherwise, I'll force merge

**Review by toku-sa-n — APPROVED** [review]

**Comment by mihaimaruseac** [comment]
Thank you! I'll cut a new release tomorrow

**Comment by toku-sa-n** [comment]
Thank you and sorry for the long delay. I'll fix the remaining warnings when I have time.

**Comment by mihaimaruseac** [comment]
No worries about the delay, I delayed this for too long myself.

**Pull request merged**
