### PR TITLE
Support GHC 9.6

### PR DESCRIPTION
**Pull request by toku-sa-n**
- [ ] Create a wrapper for `ghc-lib-parser` to handle different versions easily

Fixes: #697

### CODE REVIEW

**Comment by mihaimaruseac** [comment]
Sorry resolved conflicts wrongly

**Review by mihaimaruseac — COMMENTED** [review]
I think it worked without the last commit. Let's revert it as the macro aliases I think decrease readability

**Review by mihaimaruseac — APPROVED** [review]
Thank you!

**Comment by toku-sa-n** [comment]
Actually, this PR is still a draft. It has lots of duplicated codes, and I have to remove them.

**Comment by mihaimaruseac** [comment]
Oh, my bad :( I thought it was gone and it was timezone difference

**Comment by toku-sa-n** [comment]
No, it's because of my computer's broken clock :)
Anyway, I'll send another PRs to continue refactoring.

**Pull request merged**
