### PR TITLE
Feature/haskell src exts 1.22.0

### PR DESCRIPTION
**Pull request by sevanspowell**
- Add Pretty implementation of:
  - UnboxedSum patterns, expressions, and types (since
    haskell-src-exts 1.20.0).
  - DerivingVia (since haskell-src-exts 1.21.0).
  - Typed Template Haskell splices and expressions (since
    haskell-src-exts 1.22.0).
- Update "Pretty Asst" instance to match new "Asst" structure in
  haskell-src-exts 1.22.0.
- Move stackage snapshot to "lts-15.5" and use "MonadFail".
- Use "error" in "src/main/Test.hs" instead of "fail" as "SpecM" does
  not have an instance of MonadFail (yet).
- Remove unused functions "isRecord", "recDecl", and "qualConDecl".

### CODE REVIEW

**Comment by sevanspowell** [comment]
@chrisdone I'm unsure of how to proceed with making the job pass on older stackage snapshots. The tests are only relevant to certain GHC versions, as the code it.

I'm also not 100% sure the styling choices I've made are consistent with the rest of the project.

**Review by mihaimaruseac — APPROVED** [review]

**Review by mihaimaruseac — APPROVED** [review]
(testing CI again, now that it is fully done)

**Comment by mihaimaruseac** [comment]
So this seems to fail CI on Stack only (3/3 attempts). Will likely need more work.

**Review by mihaimaruseac — APPROVED** [review]

**Comment by mihaimaruseac** [comment]
(Testing to see if this works now. If it doesn't, will look more into this later, after the next release)

**Comment by mihaimaruseac** [comment]
Unfortunately, will have to close this since we moved to `hasell-src-exts` in #593

**Pull request closed without merging**
