### PR TITLE
Write `package.yaml` instead of `hindent.cabal`

### PR DESCRIPTION
**Pull request by toku-sa-n**
The main advantage is that we don't have to list all modules manually.

### CODE REVIEW

**Comment by mihaimaruseac** [comment]
We'll need to always generate the cabal file each time package.yaml changes. But otherwise, the idea of this lgtm

**Comment by toku-sa-n** [comment]
I thought running `stack build` generates the cabal file If necessary, but when I ran it after modifying HIndent's version to 5.3.6 in `package.yaml`, the cabal file was not changed. Maybe we need to ensure the cabal file is up-to-date on CI?

**Comment by mihaimaruseac** [comment]
Yes, I'm thinking the same

**Review by mihaimaruseac — APPROVED** [review]
Do we want to remove the files in `tests`? They don't look like doing much, so maybe yes?

**Comment by toku-sa-n** [comment]
Yes, these files do nothing. Do you prefer another PR for the deletion?

**Comment by mihaimaruseac** [comment]
It's ok here, just wanted to make sure.

**Pull request merged**
