### PR TITLE
Check the format of source files in `src/` on CI

### PR DESCRIPTION
**Pull request by toku-sa-n**
The purpose is
- To improve readability.
- To test HIndent with an actual project.
- To minimize a commit diff.

~#599~ #636 is a PR to pass all tests.

### CODE REVIEW

**Comment by mihaimaruseac** [comment]
Let's punt on this until #599 first lands since we'll need to retest CI

**Review by mihaimaruseac — APPROVED** [review]
Let's try now

**Review by mihaimaruseac — APPROVED** [review]

**Comment by toku-sa-n** [comment]
It seems like Windows' [`pwsh`](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsshell) doesn't expand asterisks. Do we add a step for Windows, or use `bash` anytime?

**Review by mihaimaruseac — APPROVED** [review]

**Comment by mihaimaruseac** [comment]
Let's go with this as it is. I'm planning a refactoring of actions over the next week and after that we can do a new release.

Thank you very much for the PRs you've sent!

**Comment by toku-sa-n** [comment]
Okay, thanks. I'm looking forward to the new release!

**Pull request merged**
