### PR TITLE
Support GHC 9.10.*

### PR DESCRIPTION
**Pull request by toku-sa-n**
### Description of the PR

Fixes: #890

### Checklist

- [ ] Add a changelog if necessary. See https://keepachangelog.com/ for how to write it.
- [ ] Add tests in [TESTS.md](/TESTS.md) if possible.

### CODE REVIEW

**Comment by mihaimaruseac** [comment]
I'm thinking of doing just one more release with GHC 8 then dropping it. Would that help for this?

**Comment by toku-sa-n** [comment]
> I'm thinking of doing just one more release with GHC 8 then dropping it. Would that help for this?

Unfortunately, no. Supporting a new GHC version is much more cumbersome than keeping support for older GHCs.
Sorry for being late, but I'll complete this PR within a week.

**Comment by mihaimaruseac** [comment]
Oh, no, no worries about being late. I didn't add a comment to say you're late on this, take as much time as you need. I'm really happy you're working on this, I just got some time to look at the repo this weekend as it is a long one.

**Comment by toku-sa-n** [comment]
Ah, sorry! Actually, I wasn't hurt, and I didn't mean to hurt you. I always appreciate your review and comments. For the comment, I understand that you just asked a question and didn't have any other intention.

**Comment by mihaimaruseac** [comment]
No worries about this at all, it's all good :) I really like seeing your work on this!

**Comment by toku-sa-n** [comment]
So late, and so huge diff, but at least the code now compiles and passes tests with GHC 9.10. I plan to submit clean-up PRs later.

**Review by mihaimaruseac — APPROVED** [review]
This was heroic amounts of work! Thank you

**Comment by toku-sa-n** [comment]
Thanks for the merge! Could you create a new release? A few changes are not released yet, and this might be a good timing for it.

**Comment by mihaimaruseac** [comment]
Sure, I'll do it tomorrow first thing. Thanks for the reminder!

**Comment by toku-sa-n** [comment]
Thanks for the release!

**Pull request merged**
