### PR TITLE
Fix not all `.hs` files are traversed

### PR DESCRIPTION
**Pull request by toku-sa-n**
### Description of the PR

Do `shopt -s globstar` before self-validation.

### Checklist

- [x] Add a changelog if necessary. See https://keepachangelog.com/ for how to write it.
- [x] Add tests in [TESTS.md](/TESTS.md) if possible.

### CODE REVIEW

**Review by mihaimaruseac — APPROVED** [review]

**Comment by mihaimaruseac** [comment]
This seems to also try to format files in `dist-newstyle` :( Maybe let's do a `find ... -not ... -exec` command instead?

**Comment by toku-sa-n** [comment]
Yeah I'm aware of it, and going to fix (haven't done it yet because I was skiing for two days :)

**Comment by mihaimaruseac** [comment]
There's no rush ;) Enjoy skiing!

**Review by mihaimaruseac — APPROVED** [review]
Awesome! Thank you

**Pull request merged**
